//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GstPlayground.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool upgradeNeeded {
            get {
                return ((bool)(this["upgradeNeeded"]));
            }
            set {
                this["upgradeNeeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <SerializableStringDictionary>
                        <Pair Name=""testsrc"" Value=""videotestsrc ! queue ! videoconvert ! d3d11videosink name=prevSink"" />
                        <Pair Name=""testsrcauto"" Value=""videotestsrc ! queue ! videoconvert ! autovideosink name=prevSink"" />
                        <Pair Name=""rtsp1"" Value=""gst-launch-1.0.exe rtspsrc location=rtsp://192.168.0.226:554/Videoinput/1/h264/1 latency=0 drop-on-latency=true ! rtph264depay ! h264parse ! d3d11h264dec ! videoconvert ! autovideosink"" />
                        <Pair Name=""d3dball"" Value=""d3d11compositor name=c ! d3d11videosink videotestsrc ! video/x-raw,width=320,height=240 ! c. videotestsrc pattern=ball ! video/x-raw,width=100,height=100 ! c."" />
                    </SerializableStringDictionary>
                ")]
        public global::GstPlayground.SerializableStringDictionary launchDict {
            get {
                return ((global::GstPlayground.SerializableStringDictionary)(this["launchDict"]));
            }
            set {
                this["launchDict"] = value;
            }
        }
    }
}
